TINY: tiny.c csapp.c
	gcc -O2 -o TINY tiny.c csapp.c -lpthread
TINY_6: tiny_6.c csapp.c
	gcc -O2 -o TINY_6 tiny_6.c csapp.c -lpthread
adder: adder.c csapp.c
	gcc -O2 -o web/cgi-bin/adder adder.c csapp.c -lpthread
clean:
	rm TINY*
